### ISSUE TITLE
[v6.4.0] Master node does not send cached data to mirror node

### ISSUE THREAD

**Issue by H1r0Sh1mA** [Unity-Technologies/unity-cache-server#170]
I have simple 2 nodes topology: master node - mirror node(ip addr: 192.168.77.12).
Servers can access each other on default port 8126.

My config yml:
```
Cache:
  defaultModule: cache_fs
  options:
    processor:
      putWhitelist: []
    cache_ram:
      cachePath: /var/lib/unity-cache-server/cache_ram
      pageSize: 100000000
      maxPageCount: 100
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
    cache_fs:
      cachePath: /var/lib/unity-cache-server/cache_fs
      cleanupOptions:
        expireTimeSpan: P30D
        maxCacheSize: 0
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
Mirror:
  addresses: [192.168.77.12]
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
Server:
  port: 8126
  options:
    allowIpv6: false
Global:
  logLevel: 4

```
During the unity-cache-server startup on master node i  see the following entries in log:
```
unity-cache-server ucs[27713]: [Cluster:M] [TransactionMirror] Mirroring transactions to 192.168.77.12:8126
unity-cache-server ucs[27713]: [Cluster:1] [TransactionMirror] Connecting to 192.168.77.12:8126
```
On my mirror node, using tcpdump i can see that the master node is sending initial handshake.
The problem is:
When unity sends data to the master node cache the data reflects on master node only and doesnt sending on mirror node.
I have also tried to start unity-cache-server service on master node like this:
```
node /usr/bin/unity-cache-server --workers 1 --mirror 192.168.77.12:8126  --cache-module cache_fs --NODE_CONFIG_DIR=/etc/unity-cache-server
```
After it started up i can see this process in process tree with --mirror 192.168.77.12:8126 option , but the cached data doesnt reflects on mirror node either.
