### ISSUE TITLE
Dump cache_ram to fs every so often?

### ISSUE THREAD

**Issue by partounian** [Unity-Technologies/unity-cache-server#55]
Is there a way to get performance of ram cache but some level of persistence? Our local build machine restarts nightly, and I was wondering if I can persist the data on some interval that way I don't cold start daily.

**Comment by stephen-palmer** [comment]
The default configuration does this for you automatically. It persists in 10 second intervals, only if there are any changes. The data is saved to the `.cache_ram` subfolder (usually, unless you've specified a cache folder on the CLI)

So I'm assuming this is not working for you for some reason .. first check you config file and look for these options:

```Cache:
  options:
    cache_ram:
          persistence: true
          persistenceOptions:
            autosave: true
            autosaveInterval: 10000
```

**Comment by partounian** [comment]
```
Cache:
  defaultModule: "cache_ram"
  options:
    cache_ram:
      cachePath: ".cache_ram"
      pageSize: 100000000
      maxPageCount: 600
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: true
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: false
        multiClient: true
```
