### ISSUE TITLE
100% CPU utilization

### ISSUE THREAD

**Issue by mleenhardt** [Unity-Technologies/unity-cache-server#68]
We're running into an issue where the cache server process starts using 100% of all available cores after a few days of utilization. Restart the process "fixes" the issue and CPU usage returns to normal. We haven't been able to identify a reason why that would happen, it doesn't seem to follow any usage pattern.

We're running 6.1.2 (was happening before on 6.1.0) on node 8.11.4 with the following command line and config file.

`/bin/unity-cache-server --workers 2 --log-level 4 --NODE_CONFIG_DIR=/path/config`

```
Cache:
  defaultModule: "cache_fs"
  options:
    processor:
      putWhitelist: []
    cache_ram:
      cachePath: ".cache_ram"
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
    cache_fs:
      cachePath: "/path"
      cleanupOptions:
        expireTimeSpan: "P30D"
        maxCacheSize: 140000000000
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: false
        multiClient: false
Mirror:
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
Server:
  port: 8126
  options:
    allowIpv6: false
```
