### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by SGDavid** [Unity-Technologies/unity-cache-server#95]
This is new in v6.2.3, I am pretty certain.
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100063a65 node::Abort() [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 2: 0x100064104 node::errors::TryCatchScope::~TryCatchScope() [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 3: 0x10019d9a7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 4: 0x10019d944 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 5: 0x1005a2122 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 6: 0x1005a4653 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 7: 0x1005a0b88 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 8: 0x10059ed45 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
 9: 0x1005a7a7b v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
10: 0x1005b8e6f v8::internal::IncrementalMarkingJob::Task::RunInternal() [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
11: 0x1000ba156 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task> >) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
12: 0x1000b987a node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
13: 0x1009fbd2f uv__async_io [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
14: 0x100a0b898 uv__io_poll [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
15: 0x1009fc1b6 uv_run [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
16: 0x100048371 node::Start(v8::Isolate*, node::IsolateData*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
17: 0x10004784c node::Start(uv_loop_s*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
18: 0x1000474b2 node::Start(int, char**) [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
19: 0x100001034 start [/Users/cache/node-v11.6.0-darwin-x64/bin/node]
```

**Comment by stephen-palmer** [comment]
What stands out immediately to me is that you're running node v11.6 .. we're still on v8.12 LTS.

**Comment by SGDavid** [comment]
I'll downgrade tonight.

**Comment by stephen-palmer** [comment]
Required. I wanted to move to v10 (latest LTS) but there are some incompatibilities that require investigation and fixing.

**Comment by mleenhardt** [comment]
We haven't yet seen an OOM error but have noticed a massive increase in RAM consumption with 6.2.3. We're using the fs module and are seeing each 8 node workers that we're running consuming up to 1.5GB of RAM. I'm under the impression that workers were barely using any RAM on 6.2.0.

We're running node 10.13.

**Comment by stephen-palmer** [comment]
@mleenhardt we don't support node v10 yet. Not saying that would make a difference in RAM usage but please use the version specified in the package.json file (or .nvmrc)

**Comment by stephen-palmer** [comment]
Published a fix for the worker memory leak in v6.2.4-beta2

**Comment by stephen-palmer** [comment]
Fixed in v6.2.4 (published to NPM)

**Comment by corngood** [comment]
We upgraded from 6.1.2 to 6.2.4 and we're seeing a huge increase in memory use.  We have four workers, and after a day they are each using between 1.5 and 3.5GB of physical memory.  This is on node 8.14 on linux.

**Comment by stephen-palmer** [comment]
I'll investigate further, thanks for reporting.

**Comment by corngood** [comment]
Here's the log for that run (until I killed when it was using ~8GiB) in case it's useful: https://clbin.com/IsNpN

How much memory use are you seeing at the process level?  6.1.2 has been running since I restarted it this morning and it's using about 100MiB (physical) / worker.

**Comment by stephen-palmer** [comment]
I saw a high watermark of about 190M, settling back to about 150M at idle. I'm going to let this run for a while and keep pounding on it to see if it's a slow leak.

Thanks for the log - that crash in there should be fixed as well.

**Comment by stephen-palmer** [comment]
I also see `Cannot read property 'clientAddress' of null` in your log - will look into that as well.

**Comment by stephen-palmer** [comment]
@SGDavid what are you seeing in terms of memory consumption in 6.2.4?

**Comment by SGDavid** [comment]
Looks like ~250MB for an active process and ~95MB for an idle process. Node.js v8.12.0 on a Mac Mini

**Comment by stephen-palmer** [comment]
That seems normal. Maybe a platform specific issue after all.

**Comment by SGDavid** [comment]
The cache server I assessed (I have four in three different locations) can experience very heavy load at times. It has not had a single issue since the 6.2.4 release.

**Comment by stephen-palmer** [comment]
I did some profiling today against a Linux server (using Docker) and I'm seeing similar memory usage to MacOS. Not really sure where to go from here in terms of troubleshooting, unless someone else can chime in for some more evidence.

**Comment by corngood** [comment]
@stephen-palmer thanks for investigating.  I'll try again and see if I can reproduce it with the memory profiler.

**Comment by corngood** [comment]
In case you're interested, here's what I was seeing:

[memory use](https://i.imgur.com/VG6p93s.png)

The big spike with all the swap was when I was testing 6.2.4 on node 10.  The smaller spike on the 14/15th was 6.2.4 on node 8.14.  Since the 15th I've been using 6.1.2 on node 8.14, which seems to be ok with memory, but suffers from #68.

**Comment by corngood** [comment]
I had another try today.  Same version of node (8.14), with 6.2.4.  This is from `top` after about 6 hours.

```
24525 unityca+  20   0 5219092 3.833g   5216 S   0.0 24.6   4:27.55 node
24532 unityca+  20   0 2198016 1.073g   4940 S   0.0  6.9   2:41.22 node
24526 unityca+  20   0 3160652 0.979g   5036 S   0.0  6.3   2:35.36 node
24531 unityca+  20   0  983732  72036   4820 S   0.0  0.4   0:07.33 node
24514 unityca+  20   0  981948  69876   4912 S   0.0  0.4   0:56.87 unity-cache-ser
```

The server's starting to swap, so I'm going to have to revert for now.  I haven't had time to do any profiling, unfortunately.

**Comment by corngood** [comment]
Sure, here's my config.yml:
```yaml
Cache:
  defaultModule: cache_fs
  options:
    processor:
      putWhitelist: []
    cache_ram:
      cachePath: .cache_ram
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
    cache_fs:
      cachePath: "/mnt/fast/unitycache/cache5.0"
      cleanupOptions:
        expireTimeSpan: P30D
        maxCacheSize: 180000000000
Mirror:
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
```

and the output of --dump-config:

```yaml
Cache:
  defaultModule: cache_fs
  options:
    processor:
      putWhitelist: []
    cache_ram:
      cachePath: .cache_ram
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
    cache_fs:
      cachePath: .cache_fs
      cleanupOptions:
        expireTimeSpan: P30D
        maxCacheSize: 0
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
Mirror:
  addresses: []
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
Server:
  port: 8126
  options:
    allowIpv6: false
Global:
  logLevel: 3
```
